apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: aiops-reader-binding
  namespace: default

subjects:
  - kind: ServiceAccount
    name: aiops-agent
    namespace: default

roleRef:
  kind: Role
  name: aiops-reader
  apiGroup: rbac.authorization.k8s.io

